id: P007989
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2546
  title: སྐལ་ལྡན་གྱི་སློབ་བུའི་ཚོགས་ལ་གདམས་པ་བསླབ་བྱའི་སྐོར་བླང་དོར་གསལ་སྒྲོན
  author: ''
  volumes:
    3043a8af369748829ee42d200a26c4d0:
      image_group_id: I1CZ2714
      title: ''
      volume_number: 1
      total_pages: 100
ebook_metadata:
  title: སྐལ་ལྡན་གྱི་སློབ་བུའི་ཚོགས་ལ་གདམས་པ་བསླབ་བྱའི་སྐོར་བླང་དོར་གསལ་སྒྲོན
  author: ''
  sku: P007989
  cover: cover.jpg
  layers:
  - pagination
