id: P007989
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:40.082056
source_metadata:
  id: bdr:W1CZ2546
  title: སྐལ་ལྡན་གྱི་སློབ་བུའི་ཚོགས་ལ་གདམས་པ་བསླབ་བྱའི་སྐོར་བླང་དོར་གསལ་སྒྲོན
  author: ''
  volumes:
    c2a451b24a11461f9e33fe06d4092e2f:
      image_group_id: I1CZ2714
      title: Volume 1 of skal ldan gyi slob bu'i tshogs la gdams pa bslab bya'i skor
        blang dor gsal sgron
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
